[webservers]
web-1 ansible_host=192.168.2.2 ansible_user=ubuntu
web-2 ansible_host=192.168.2.3 ansible_user=ubuntu

[dbservers]
db-1 ansible_host=192.168.2.4 ansible_user=ubuntu

[lbservers]
lb-1 ansible_host=192.168.2.5 ansible_user=ubuntu

[webservers:vars]
ansible_ssh_private_key_file=/Users/mamboota/.ssh/multipass_ansible

[dbservers:vars]
ansible_ssh_private_key_file=/Users/mamboota/.ssh/multipass_ansible

[lbservers:vars]
ansible_ssh_private_key_file=/Users/mamboota/.ssh/multipass_ansible
